.github/workflows/chart-lint.yml, .github/workflows/chart-releaser.yaml, .github/workflows/deploy-staging.yaml
Just saw that these headers are missing.
=> add eclipse license header to workflow files

Dockerfile
Add HEALTHCHECK in Dockerfile.
Queries the MIW Spring-Boot liveness actuator endpoint .
=> feat(docker): add healthcheck in Dockerfile

.github/workflows/docker-hub-release.yaml, Docker-hub-notice.md
Adds the GH Action workflow to release the Docker image to Tractus-X Docker Hub.
It also updates the description according https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06/
=> feat: add Docker Hub release workflow

.tractusx
This PR adds the initial repo metadata file described in [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5).
This info is used to collect information about products contained in Eclipse Tractus-X
=> docs: add initial repo metadata

DEPENDENCIES, NOTICE.md, build.gradle, src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IssuersCredentialService.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/service/PresentationService.java, src/test/java/org/eclipse/tractusx/managedidentitywallets/config/TestContextInitializer.java, src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java, src/test/java/org/eclipse/tractusx/managedidentitywallets/vp/PresentationTest.java
chore: update the `cx-ssi-lib` from <https://github.com/catenax-ng/product-lab-ssi/tree/main/cx-ssi-lib> to `0.0.16`and the `DidDocumentResolverRegistry` has been migrated to the `DidResolver` interface
fix: a flaky bug in the private key generation for tests has been fixed
docs: a notice has been added to explicitly document the usage of the `cx-ssi-lib`
=> Update ssi lib version

CHANGELOG.md.jinja
This fix removes all links to remote repos from the generated CHANGELOG.md file. 
=> fix: remove all links to remote repos from CHANGELOG.md

CHANGELOG.md.jinja
Adds the Eclipse Copyright header to the generated CHANGELOG.md file.
=> feat: add Eclipse Copyright header to CHANGELOG.md.jinja

.github/workflows/dast-scan.yaml
This PR introduce a DAST API scan with ZAP (https://github.com/zaproxy/zaproxy)
Currently there is no authentication done. This should simulate a "normal" attack against the API.
The app is deployed in a local KinD cluster and the ZAP scan is running outside it - as a standalone docker container.
The MIW app is exposed via `kubectl port-forward`, so that ZAP can access it.
=> ci: add DAST scan workflow

.github/workflows/dast-scan.yaml, src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/HoldersCredentialController.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/IssuersCredentialController.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/PresentationController.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/WalletController.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/service/DidDocumentResolverService.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IssuersCredentialService.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/service/PresentationService.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/service/WalletKeyService.java, src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java, src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/PresentationValidationTest.java
Fix rate limit during json-ld context loading.
Changes
- make use of DidDocumentResolver from the ssi library 0.0.17
- this version supports context caching
- had to change some things, so that the code still compiles
- added logging for all incoming http calls
- it was not possible to see what the MIW was doing on int
- repaired tests
- added a valid did to a test
- added a default vc expiry date to test setup
=> fix: rate limit during json-ld context loading

.github/workflows/release.yml, .releaserc
Fixed the helm chart release.
Changes
- Replaced Github `chart-releaser` action with plain helm command line, because the chart-releaser action wanted to create a release (which already exists)
- Increment the `version` in the Chart.yaml now too, cause it defines the name of the zip file
=> fix(ci): helm chart release

charts/managed-identity-wallet/Chart.yaml
This PR simply adds a second Helm chart maintainer.
=> chore(helm): add a second maintainer

charts/managed-identity-wallet/README.md, charts/managed-identity-wallet/templates/deployment.yaml, charts/managed-identity-wallet/values.yaml
Adding an option to specify `initContainers` to the miw Helm chart.
We e.g. have a usecase to add a initContainer for the miw Helm.
This will allow our miw to register itself at the database and the initialising script can be triggered.
<hr />
Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))
=> feat: add initContainers

INSTALL.md, README.md, dev-assets/docker-environment/docker-compose.yaml, dev-assets/env-files/env.docker.dist, dev-assets/env-files/env.local.dist, dev-assets/scripts/get_Token.sh
This PR updates updates content in the "Developer documentation" section and introduces INSTALL.md.
This file describes the actions needed, to just run MIW.  Nothing else.
Beside that main purpose of the PR, there are some minor adjustments / fixes, which popped up during the verification of the README.md file.
This PR fixes #150 
=> Update README.md, introduce INSTALL.md

DEPENDENCIES, Dockerfile
This PR will add the legal documentation as per TRG 7.05 to the docker container.
This is meant to comply with issue #171 
=> Add legal documentation to docker container

.github/workflows/chart-verification.yml, charts/managed-identity-wallet/Chart.lock, charts/managed-identity-wallet/README.md
TRG 5.11 requires a manual trigger for testing the Helm chart. The trigger has been extended to include an optional input which lets the user select a kind version when manually running the workflow.
Closes #68 
=> chore: add node_image input for kind cluster step

charts/managed-identity-wallet/.helmignore, charts/managed-identity-wallet/Chart.lock, charts/managed-identity-wallet/Chart.yaml, charts/managed-identity-wallet/README.md, charts/managed-identity-wallet/templates/_helpers.tpl, charts/managed-identity-wallet/templates/pgAdmin-server-definitions.yaml, charts/managed-identity-wallet/values.yaml
This PR configures the pgadmin Helm chart for usage inside the MIW Helm chart as part of the series of PRs to implement issue #147 
Pgadmin is disabled by default, so it has to be enabled / configured in the values.yaml.
A default user / password is set. (The pgadmin chart itself sets also a default password, which is overwritten here)
Beside that, the MIW Postgresql DB is preconfigured and can be instantly used. You just have to provide the password for the DB.
This can be addressed in a new issue / PR.
Replaces #189 
=> feat(helm): configure MIW Helm chart to use pgadmin4 subchart

index.yaml
Removing invalid release inside repo index.
fixes #204
=> fix(helm): remove Helm release v1.1.0

.releaserc
This PR will start updating the information in the chart `README.md` file. This is in accordance with TRG 5.02
The `semantic-release` creates release commits and pre-release commits, which changes the current version of the released chart. This information is also contained in the `charts/managed-identity-wallet/README.md`, but was never updated by `semantic-release`. By adding a new `exec` section to the `.releaserc` file, we can generate the up-to-date readme and add it to the release commit.
Closes #153 
=> ci: add charts readme to semantic release

.github/workflows/release.yml
The previous PR #217 did not include `helm-docs` during a semantic release commit. This PR adds a step right before the semantic release.
=> fix: missing helm docs during semantic release

.github/workflows/release.yml
TRG 6.01 requires to add the released helm chart to the current GitHub release. This step uses `gh` which is installed by default on all runners.
=> ci: upload helm asset to release

src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/VerifiableCredentialIssuerEqualProofSignerTest.java
> This PR is set to develop.
> For the main branch I opened https://github.com/eclipse-tractusx/managed-identity-wallet/pull/185. The develop PR remains in draft state until this is merged.
-- NOT RELEVANT
- Set SSI library version to 0.0.18-SNAPSHOT.
- This library has a fix that asserts, that the verifiable credential signer must also be the issuer.
-- NOT RELEVANT (borisrizov-zf)
- Add Unit Test to verify fix
<hr/>
<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>
=> chore: add test to check verifiable credential issuer equals signer

charts/managed-identity-wallet/README.md, charts/managed-identity-wallet/tests/custom-values/deployment_test.yaml, charts/managed-identity-wallet/tests/default/deployment_test.yaml, charts/managed-identity-wallet/values.yaml
Minor fixes in the helm chart.
- removed `Chart.lock` from git
- postgresql chart install condition pointed to wrong value
- typo: renamed `conjob` to `cronjob`
Improvements:
- `secretPasswordKey` default value is now set to default bitnami postgres secret value, so it can be used out of the box.
- `postgresPassword` value for the database admin is now part of the chart, in case the user wants to set it.
=> fix(helm): minor fixes

charts/managed-identity-wallet/README.md, charts/managed-identity-wallet/templates/networkpolicy.yaml, charts/managed-identity-wallet/values.yaml
This PR will add a [networkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to restrict the access to the miw pods.
In the default implementation access from every namespace is allowed (empty ns selector):
```yaml
from:
- namespaceSelector: {}
```
We also need this change to allow network traffic because the default setting will deny everything.
Other [etx repos](https://github.com/eclipse-tractusx/tractusx-edc/blob/afad91dcf52d747274b0e82ea0f502d41c7b7a34/charts/tractusx-connector/templates/networkpolicy.yaml) already use networkPolicies.
I would be delighted if this could be merged and released soon.
<hr />
<sub>Marco Lecheler …
=> feat(helm): add networkPolicy for miw

charts/managed-identity-wallet/templates/networkpolicy.yaml
As the networkPolicy was introduced in #246 it works as expected.
But for our usecase we need to restrict the networkPolicy to the installed namespace.
This is possible if the namespace will be selected with a matching label.
Therefore the use of the variable `.Releases.Namespace` is a common approach.
With the current implementation templating of the values are not allowed.
This change will allow to template the values files (with a bitnami-common helpers).
```yaml
networkPolicy:
enabled: true
from:
- namespaceSelector:
matchLabels:
kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
```
Without this PR the matchLabels would not be templated and still result in:
`kubernetes.io/metadata.name: "{{ .Release.Namespace }}"`
With these changes the result would be e.g.: …
=> feat(helm): allow networkPolicy to template values

src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/SecurityConfig.java, src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/SecurityEvents.java
The MIW doesn't log anything when a request requiring auth is missing the Authorization header. Two event listeners will be added to handle the missing header, or to handle the invalid header.
Closes #83 
=> feat: add logging of auth failures

.github/workflows/release.yml
The CI currently does not upload the produced jar to the official GH release. This PR fixes this issue.
Fixes #202 
=> Feature: upload jar artifact to release

CONTRIBUTING.md, README.md
The tool `semantic-release` has its own workflow, which is not well documented in this repo. This PR will add documentation for new developers and committers alike, which will aid them when creating/reviewing new PRs.
Closes #199  
=> chore: add contribution docs and committer docs

miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/constant/StringPool.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/service/JwtPresentationES256KService.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/wallet/WalletTest.java
This is an implementation of enhancements: did document fields and "add service entry for token endpoint".
More details in #292, #296
=> feat: did document update

miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/PresentationIatpFilter.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/SecurityConfig.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/constant/RestURI.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/PresentationController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/PresentationResponseMessage.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/reader/TractusXJsonLdReader.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/reader/TractusXPresentationRequestReader.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/utils/ResourceUtil.java, miw/src/main/resources/jsonld/IdentityMinusTrust.json, miw/src/main/resources/jsonld/identity.foundation.presentation-exchange.submission.v1.json, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/dto/PresentationResponseSerializationTest.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/identityminustrust/TokenRequestTest.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/reader/PresentationRequestReaderTest.java, miw/src/test/resources/identityminustrust/messages/presentation_query.json
- IATP endpoint `/api/presentations/iatp` endpoint now accepts PresentationQueryMessage and returns PresentationResponseMessage objects.
- Changed HTTP Method of `/api/presentations/iatp` from GET to POST
- add hidden endpoint IATP endpoint `/presentations/query` for EDC compatibility reasons
<hr/>
<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>
=> feat(identity-trust)!: update IATP protocol

gradle.properties, miw/DEPENDENCIES, miw/build.gradle
Spring boot and cloud lib version was updated to mitigate https://github.com/advisories/GHSA-f3jh-qvm4-mg39
This PR is qual to https://github.com/eclipse-tractusx/managed-identity-wallet/pull/277 from a different merge source
=> fix: updated spring boot and cloud version

miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/CustomAuthenticationEntryPoint.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/SecurityConfig.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/SecurityEvents.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/constant/StringPool.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/HoldersCredentialController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/IssuersCredentialController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/PresentationController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/WalletController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/utils/BpnValidator.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/utils/TokenParsingUtils.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/config/CustomAuthenticationEntryPointTest.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/utils/BpnValidatorTest.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/utils/TokenParsingUtilsTest.java
This is implementation of Feature: BPN authorisation validation
Ref #278 
=> feat: bpn auth validation

miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/HoldersCredentialController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/IssuersCredentialController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/PresentationController.java, miw/src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/PresentationResponseMessage.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/utils/TestUtils.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/IssuersCredentialTest.java, miw/src/test/java/org/eclipse/tractusx/managedidentitywallets/vp/PresentationTest.java
> BREAKING CHANGE
All API endpoints that used Verifiable Credentials and -Presentations in JSON format per default are now working with the JWT format by default instead. Additionally, fixed error in IATP endpoint.
Closes #344
<hr/>
<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>
=> feat(API)!: change API VC/VP default data format from Json to JWT 
