- README.md
---
name: Add overview of available roles associated to the available endpoints
about: 'template for PRs that ensures basic information is provided'
title: '(feat)(doc): adds overview of roles associated with available endpoints'
---
Enhances the README.md with an overview associating the available roles of MIW to the (currently) available endpoints of MIW.
> feat: adds overview of roles associated with available endpoints

- .github/workflows/semantic-release.yml
- .releaserc
PR for semantic release github ci pipeline.
This workflow goes through the conventional commits and
- generates a new version number
- creates a commit with the
- upgraded version in gradle and helm
- updated the CHANGELOG.md
> ci(semantic-versioning): introduce semantic version workflow

- .github/workflows/docker-hub-release.yaml
This PR takes care of two little things:
1. Publish "latest" tag when Docker Hub Release workflow pushes images to Tractus-X Docker Hub. (ref: https://github.com/eclipse-tractusx/managed-identity-wallet/pull/76#issuecomment-1705316816)
2. Run Docker Hub Release workflow on PR only on specific folders ('Dockerfile' and 'src/main/**')
-> because this workflow is running unnecessarily on every PR.
> feat: update Docker Hub release workflow

- .github/workflows/trivy.yml
Trivy pulls image from Docker Hub and scans image.
> chore: update trivy.yml

- charts/managed-identity-wallet/tests/custom-values/deployment_test.yaml
- charts/managed-identity-wallet/tests/default/deployment_test.yaml
- charts/managed-identity-wallet/values.yaml
Fix:
HTTPS should be mandatory while resolving did document, so proposing the default value as true
> fix:default enforceHttpsInDidWebResolution set to true

- src/main/java/org/eclipse/tractusx/managedidentitywallets/service/WalletService.java
Fix:
The application starts with corrupted data in case of an invalid AES key. 
The reason is `@Transactional` is not working  with `@PostConstruct` annotation.  We need to handle rollback manually.
> fix: CGD-468: Application starts with corrupted data in case of invalid AES key

- DEPENDENCIES
- build.gradle
- src/main/java/org/eclipse/tractusx/managedidentitywallets/config/ExceptionHandling.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/constant/StringPool.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/CreateWalletRequest.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/IssueDismantlerCredentialRequest.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/IssueMembershipCredentialRequest.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/utils/CommonUtils.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/did/DidDocumentsTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/utils/TestUtils.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/DismantlerHoldersCredentialTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/FrameworkHoldersCredentialTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/IssuersCredentialTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/MembershipHoldersCredentialTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/PresentationValidationTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/vp/PresentationTest.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/wallet/WalletTest.java
1. BPN validation using regex
2. Better exception handling to avoid internal server error 
3. Unitlize ExceptionUtils to send a short error message
4. Test case modification
> feat(validation and error handling): BPN validation with regex and better error handling

- .github/workflows/chart-lint-test.yml
- .github/workflows/chart-releaser.yaml
- .github/workflows/kics.yml
- .github/workflows/semantic-release.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yaml
This is a complete check of all GH workflows. What was checked and updated:
- Workflow naming 
- action's version (and config when required)
- workflow's agent
- trigger branch names
> chore: update or pin action versions, workflow naming and action's config

- dev-assets/tasks/linux/app.yaml
Typo error fixed in Bearer for local setup
> fix: typo in Bearer

- README.md
The main README.md was malformed due to the usage of backtick-quoted anchor links. This PR fixes the issue.
Closes #107 
- [ x ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
> docs: remove invalid anchor tags in readme

- .github/workflows/release.yml
Closes #110 
- [ x ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
> fix: missing env variables in release workflow

- DEPENDENCIES
- build.gradle
- gradle.properties
Update package dependencies to mitigate known security issues (including cx-ssi-lib).
> Chore update dependencies

- charts/managed-identity-wallet/README.md
This PR will update the current version of the application in the charts README.md.
This is done to comply with TRG 5.02 and fixes #153 
> chore: update Version and AppVersion in chart readme

- CHANGELOG.md
- DEPENDENCIES
Use an intermediate branch to do the merge locally. I've tried to keep some sort of time coherence and logic in the CHANGELOG and upgrade the version correctly.
> Merge main into develop

- DEPENDENCIES
- docs/ArchitectureWebDID.md
- docs/Development.md
- docs/MIW_DB_Schema_v0.0.1.md
- docs/security-assessment/security-assessment-23-12.md
Add notice post-amble to the files in the `docs/` directory. This is in accordance with TRG 7.07
Closes #70 
> doc: add legal notice to docs files

- charts/managed-identity-wallet/Chart.yaml
- charts/managed-identity-wallet/README.md
As I leave the project, I update the maintainers of the MIW Helm chart.
> chore(helm): remove chart maintainer and update chart README.md

- .github/workflows/release.yml
This fixes an issue with the release pipeline, where a newer version if `node` is required by the `semantic-release` tool.
Closes #237 
> fix(ci): update node version to 20

- src/main/java/org/eclipse/tractusx/managedidentitywallets/service/HoldersCredentialService.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/utils/CommonUtils.java
changing the current files by adding the if statement to check if there is an expiration date or not, it wont through an excpetion from Date.from(null)
or from date.toInstant()
#221 
> fix:add if statement for creating VC to check expiration date

- charts/managed-identity-wallet/README.md
- charts/managed-identity-wallet/tests/custom-values/deployment_test.yaml
- charts/managed-identity-wallet/tests/default/deployment_test.yaml
- charts/managed-identity-wallet/values.yaml
Just a minor fix regarding the helm chart values documentation.
> doc: fix extra env variables description in helm chart

- .github/workflows/veracode.yaml
The veracode action uses an outdated version of the gradle-build-action. This will update it.
> fix: possible caching vulnerability in action

- README.md
This is a small, but necessary notice, pointing out that the MIW currently needs egress to the internet to operate correctly.
Fixes #114 
> docs: add notice about egress for JSON-LD

- src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/utils/CommonUtils.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/validator/SecureTokenRequestValidator.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenControllerTest.java
This is implementation of Feature: Refactor body type in token endpoint
Closes: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/286
> feat: added body type to /token endpoint

- src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
- src/main/java/org/eclipse/tractusx/managedidentitywallets/domain/StsTokenResponse.java
- src/test/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenControllerTest.java
- Fix STS Token API Response Status `200`.
- Fix STS Token API Response Body Schema.
Closes #294 
> Fix STS Token API Response
